#!/bin/bash
# =============================================================
# Temus Tools — Deploy Script
# Usage: ./deploy.sh [dev|uat|feature/<N>-...]
# Requirements: AWS CLI configured, .env filled in
# =============================================================

set -e

TARGET=${1:-"dev"}
source .env 2>/dev/null || true

echo "🏗️  Building Next.js..."
npm run build

if [ $? -ne 0 ]; then
  echo "❌ Build failed. Stopping deployment."
  exit 1
fi

if [ "$TARGET" = "uat" ]; then
  echo "🚀 Deploying to UAT..."
  aws s3 sync ./out "s3://$AWS_S3_BUCKET_UAT" --delete --region "$AWS_REGION"
  aws cloudfront create-invalidation \
    --distribution-id "$CF_DISTRIBUTION_UAT" \
    --paths "/*"
  echo "✅ UAT deployment successful!"
  echo "🌐 URL: $AWS_CLOUDFRONT_URL_UAT"
else
  echo "🚀 Deploying to DEV (branch: $TARGET)..."
  aws s3 sync ./out "s3://$AWS_S3_BUCKET_DEV" --delete --region "$AWS_REGION"
  aws cloudfront create-invalidation \
    --distribution-id "$CF_DISTRIBUTION_DEV" \
    --paths "/*"
  echo "✅ DEV deployment successful!"
  echo "🌐 URL: $AWS_CLOUDFRONT_URL_DEV"
fi

# project.md is regenerated by the AI agent after deploy
# (see commands/deploy.md step 4)
