#!/bin/bash
# =============================================================
# Temus Tools — Generate project.md
# Regenerates project.md from project.config + GitLab API.
# Run this anytime to get the latest project state.
# Usage: bash .temus-tools/scripts/generate-project-md.sh
# =============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SCRIPT_DIR/project.config"
ENV_FILE="$PROJECT_ROOT/.env"
OUTPUT_FILE="$SCRIPT_DIR/project.md"

# --- Load config and credentials ---
if [ ! -f "$CONFIG_FILE" ]; then
  echo "❌ project.config not found. Run project init first."
  exit 1
fi
source "$CONFIG_FILE"
source "$ENV_FILE"

GITLAB_API="$GITLAB_URL/api/v4"
PROJECT_ID="$GITLAB_PROJECT_ID"

# --- Fetch feature issues from GitLab ---
FEATURES=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
  "$GITLAB_API/projects/$PROJECT_ID/issues?labels=feature&per_page=100" 2>/dev/null)

# --- Fetch merge requests ---
MERGE_REQUESTS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
  "$GITLAB_API/projects/$PROJECT_ID/merge_requests?per_page=100&state=all" 2>/dev/null)

# --- Fetch branches ---
BRANCHES=$(git fetch origin 2>/dev/null; git branch -a 2>/dev/null | grep "feature/" | sed 's/.*feature\//feature\//' | sort -u)

# --- Build feature table ---
FEATURE_TABLE=""
if echo "$FEATURES" | grep -q '"iid"'; then
  FEATURE_TABLE=$(echo "$FEATURES" | grep -oP '\{[^{}]*\}' | while read -r issue; do
    IID=$(echo "$issue" | grep -oP '"iid":\K[0-9]+')
    TITLE=$(echo "$issue" | grep -oP '"title":"[^"]*"' | head -1 | sed 's/"title":"//;s/"$//')
    STATE=$(echo "$issue" | grep -oP '"state":"[^"]*"' | head -1 | sed 's/"state":"//;s/"$//')
    # Find matching branch
    BRANCH=$(echo "$BRANCHES" | grep "feature/${IID}-" | head -1)
    [ -z "$BRANCH" ] && BRANCH="—"
    echo "| $IID | $BRANCH | $TITLE | $STATE |"
  done)
fi

# --- Build MR table ---
MR_TABLE=""
if echo "$MERGE_REQUESTS" | grep -q '"iid"'; then
  MR_TABLE=$(echo "$MERGE_REQUESTS" | grep -oP '\{[^{}]*("iid":[^{}]*)\}' | head -20 | while read -r mr; do
    MR_IID=$(echo "$mr" | grep -oP '"iid":\K[0-9]+' | head -1)
    MR_TITLE=$(echo "$mr" | grep -oP '"title":"[^"]*"' | head -1 | sed 's/"title":"//;s/"$//')
    MR_STATE=$(echo "$mr" | grep -oP '"state":"[^"]*"' | head -1 | sed 's/"state":"//;s/"$//')
    SOURCE=$(echo "$mr" | grep -oP '"source_branch":"[^"]*"' | head -1 | sed 's/"source_branch":"//;s/"$//')
    TARGET=$(echo "$mr" | grep -oP '"target_branch":"[^"]*"' | head -1 | sed 's/"target_branch":"//;s/"$//')
    echo "| !$MR_IID | $SOURCE → $TARGET | $MR_TITLE | $MR_STATE |"
  done)
fi

# --- Generate project.md ---
GENERATED_AT=$(date '+%Y-%m-%d %H:%M')

cat > "$OUTPUT_FILE" << EOF
# Project: $PROJECT_NAME

> Auto-generated by \`generate-project-md.sh\` at $GENERATED_AT.
> **Do not edit manually.** Re-run the script to refresh.

## Project Information
- **Name:** $PROJECT_NAME
- **Description:** $PROJECT_DESCRIPTION
- **Local directory:** $PROJECT_PATH
- **Created at:** $CREATED_AT

## GitLab
- **Repo URL:** $GITLAB_REPO_URL
- **Project ID:** $PROJECT_ID
- **Branches:** \`main\`, \`uat\`, \`dev\`

## Feature Issues
| # | Branch | Title | Status |
|---|--------|-------|--------|
${FEATURE_TABLE:-| — | — | No features yet | — |}

## Merge Requests
| MR | Branch | Title | Status |
|----|--------|-------|--------|
${MR_TABLE:-| — | — | No merge requests yet | — |}
EOF

echo "✅ project.md regenerated at $GENERATED_AT"
